sudo: required
language: ruby
cache: bundler
rvm:
- 2.5.1
jobs:
  include:
  - stage: test
    name: rubocop
    script: bundle install & bundle exec rubocop
  - stage: test
    name: rspec
    script: gem install bundler & bundle exec rspec